mutation UpdateTutor (
  $name: String!
  $tutortype: String!
  $gender: String!
  $email: String!
  $phoneNo: String!
  $address: String!
)@auth(level: USER) {
  tutor_update(
    first:{
      where:{
        id: {eq_expr:"auth.uid"}
      }
    }
    data: {
      name: $name
      tutortype: $tutortype
      gender: $gender
      email: $email
      phoneNo: $phoneNo
      address: $address
    }
  )
}

mutation AddTutor (
  $name: String!
  $tutortype: String!
  $gender: String!
  $email: String!
  $phoneNo: String!
  $address: String!
) @auth(level: PUBLIC){
  tutor_insert(
    data: {
      name: $name
      tutortype: $tutortype
      gender: $gender
      email: $email
      phoneNo: $phoneNo
      address: $address
    }
  )
}
