

query getTutor @auth(level: USER) {
  tutors(where: { id: { eq_expr: "auth.uid" } }) {
    id
    name
    type
    gender
    email
    phoneNo
    address
  }
}

query getTutorByName($name: String!) @auth(level: PUBLIC) {
  tutors(where: { name: { eq: $name } }) {
    id
    name
    type
    gender
    email
    phoneNo
    address
  }
}



query getTutorStudents @auth(level: USER) {
  students(where: { tutor: { id: { eq_expr: "auth.uid" } } }) {
    id
    name
    type
    gender  
    dob
    email
    phoneNo
    address
    status
    tuitionLoc
  }
}


query isUrlValid($id: UUID!) @auth(level: PUBLIC) {
  registrationLinks (
    where: {
      _and: [
        { id: { eq: $id } },
        { expiryDate: { ge_expr: "request.time" } }
      ]
    }
  ) {
    id
    submitted
    expiryDate
    tutor {
      id
      name
      type
  }
  }}