query getCurrentTutor @auth(level: USER) {
  tutors(where: { id: { eq_expr: "auth.uid" } }, limit: 1) {
    id
    name
    type
    gender
    email
    phoneNumber
    address
    calendarId
  }
}

query getAllTutors @auth(level: PUBLIC) {
  tutors {
    id
    name
    type
    gender
    email
    phoneNumber
    address
    calendarId
  }
}

query getTutorByName($name: String!) @auth(level: PUBLIC) {
  tutors(where: { name: { eq: $name } }) {
    id
    name
    type
    gender
    email
    phoneNumber
    address
    subjects: tutorStudentSubjects_on_tutor {
      subject
      startTime
      endTime
      interval
      rate
    }
  }
}

query getTutorStudents @auth(level: USER) {
  students(where: { tutor: { id: { eq_expr: "auth.uid" } } }) {
    id
    name
    type
    gender
    dob
    email
    year
    phoneNumber
    parentPhoneNumber
    address
    status
    school
    subjects: tutorStudentSubjects_on_student {
      subject
      startTime
      endTime
      interval
      rate
    }
  }
}

query getStudentbyName($name: String!) @auth(level: USER) {
  students(where: { tutorId: { eq_expr: "auth.uid" }, name: { eq: $name } }) {
    id
    name
    type
    gender
    dob
    email
    phoneNumber
    parentPhoneNumber
    year
    address
    status
    subjects: tutorStudentSubjects_on_student {
      subject
      startTime
      endTime
      interval
      rate
    }
  }
}

query getStudentbyId($id: UUID!) @auth(level: USER) {
  students(where: { tutorId: { eq_expr: "auth.uid" }, id: { eq: $id } }) {
    id
    name
    type
    gender
    dob
    email
    phoneNumber
    parentPhoneNumber
    year
    address
    status
    subjects: tutorStudentSubjects_on_student {
      subject
      startTime
      endTime
      interval
      rate
    }
  }
}

query isUrlValid($id: UUID!) @auth(level: PUBLIC) {
  studentFormURLS(where: { id: { eq: $id } }) {
    id
    tutor {
      id
      name
      type
    }
  }
}
query getLessonEvents ($endLimit:Timestamp!) @auth(level: USER) {
  lessonEvents(
    where: {
      tutorStudentSubject: {
        tutor: {
          id: {
            eq_expr: "auth.uid"
          }
        }
      },
      startTime: { gt_expr: "request.time" },
      endTime: {lt: $endLimit}
    },
    orderBy: [{ startTime: ASC }],
  ) {
    id
    startTime
    endTime
    tutorStudentSubject {
      subject
      student {
        id
        name
        type
        address
      }
    }
  }
}
