query getCurrentTutor @auth(level: USER) {
  tutors(where: { id: { eq_expr: "auth.uid" } }, limit: 1) {
    id
    name
    type
    gender
    email
    phoneNumber
    address
  }
}

query getAllTutors @auth(level: PUBLIC) {
  tutors {
    id
    name
    type
    gender
    email
    phoneNumber
    address
  }
}

query getTutorByName($name: String!) @auth(level: PUBLIC) {
  tutors(where: { name: { eq: $name } }) {
    id
    name
    type
    gender
    email
    phoneNumber
    address
    subjects: tutorStudentSubjects_on_tutor {
      subject 
    }
  }
}

query getTutorStudents @auth(level: USER) {
  students(where: { tutor: { id: { eq_expr: "auth.uid" } } }) {
    id
    name
    type
    gender
    dob
    email
    year
    phoneNumber
    parentPhoneNumber
    address
    status
    subjects: tutorStudentSubjects_on_student {
      subject
    }
  }
}

query getStudentbyName($name:String!) @auth(level:USER){
  students(where:
  {tutorId:{eq_expr:"auth.uid"} 
  name:{eq:$name}})
  {
    id
    name
    type
    gender
    dob
    email
    phoneNumber
    parentPhoneNumber
    year
    address
    status
    subjects: tutorStudentSubjects_on_student {
      subject
    }
  }
}

query isUrlValid($id: UUID!) @auth(level: PUBLIC) {
  studentFormURLS(where: { id: { eq: $id } }) {
    id
    tutor {
      id
      name
      type
    }
  }
}
