
# This is a file for you to write an un-named query.
# Only one un-named query is allowed per file.
query {
  studentFormURLs{
    tutor {
      id
      name
      type
      gender
      email
      phoneNo
      address
    }
    expiryDate
    submitted
  }
}